# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d62da068e7d0c55042a79c9cfc1346351f2d47b724b7c1a22355a03c1b31feae328a1736e8c6f02fd76fcd8bbb43da04906112228a99da5528ea2d03d68bd68

test:
  secret_key_base: e0a8b0492bac7db404f051e435e741980bccab653eb045beb2b1276cbe980d9d0fbcf42399aa0e9010400b44905664439d25f9464aedcc646e74f4db08e286db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
